Added Ukrainian Translation
agateau/pixelwheels pull request #240
Opened 2022-06-02 05:09 UTC by taras-taras

Just started using git, please tell me if I did something wrong.

2022-06-02 22:07 UTC, agateau commented
Hi, thanks for this translation! It looks good, only missing a few strings.

![screenshot-2022-06-02-235555 218](https://user-images.githubusercontent.com/3575/171745757-1a3cd8b2-94d0-4bf3-9629-d0fe905d4edd.png)

![screenshot-2022-06-02-235609 754](https://user-images.githubusercontent.com/3575/171745762-b78bc1e9-1189-4607-bf95-b4ccace38d0c.png)

![screenshot-2022-06-02-235639 149](https://user-images.githubusercontent.com/3575/171745776-35e4f11a-4000-44c2-931d-22b10c304404.png)

I added a commit (b9c6fd4a80ede0021e5af4bd6e54ac386d2f0fae) to add the missing entry to languages.xml so that the game can load your translation, but the "Ukrainian" word itself should be translated in Ukrainian (it appears in the language list you see on the third screenshot). Would be great if you could update the languages.xml file. You can also tell me how to say "Ukrainian" in Ukrainian instead, and I'll do the change myself.

2022-06-04 15:03 UTC, Nickoriginal requested changes
Fix some mistypes:

2022-06-04 15:03 UTC, Nickoriginal commented on android/assets/po/uk.po
> +msgstr  "1-й "
```suggestion
msgstr  "1-й"
```

2022-06-04 15:03 UTC, Nickoriginal commented on android/assets/po/uk.po
> +msgstr  "3-й "
```suggestion
msgstr  "3-й"
```

2022-06-04 15:03 UTC, Nickoriginal commented on android/assets/po/uk.po
> +msgstr  "4-й "
```suggestion
msgstr  "4-й"
```

2022-06-04 15:05 UTC, Nickoriginal requested changes
Remove POT-Creation-Date (see https://github.com/agateau/pixelwheels/pull/233#issue-1236085874)

2022-06-04 15:05 UTC, Nickoriginal commented on android/assets/po/uk.po
> +        "POT-Creation-Date: 2022-01-17 23:21+0100\n"
```suggestion
```

2022-06-04 15:20 UTC, Nickoriginal commented on android/assets/po/uk.po
> +msgstr  "Меню: "
```suggestion
msgstr  "Меню:"
```

2022-06-11 17:57 UTC, Nickoriginal commented
Also @taras-taras, you can see https://github.com/agateau/pixelwheels/pull/228#issuecomment-1122007096 and https://github.com/agateau/pixelwheels/pull/218#issuecomment-1102194092 to learn the sense of the tricky names.

2022-07-09 21:32 UTC, agateau commented
> Looks like it is stuck... Closing or trying to merge?

I already tried to reach out to Taras but haven't heard back yet. I am going to leave this PR open for now. It's too late for 0.23.0 anyway, but a few translations are outdated, so I may do a 0.23.1 in a month if I can get a few of them updated. If I heard from Taras in the mean time, this can be merged.

2022-09-10 08:12 UTC, agateau commented
Sadly, this PR looks it's not moving anymore :/. Closing it for now.

2022-09-10 08:12 UTC, closed without merging