Added Portuguese translation
agateau/pixelwheels pull request #263
Opened 2022-09-04 16:45 UTC by promoreira

Just a small contribution!!

2022-09-10 07:45 UTC, agateau commented
Hey, sorry for the late review. Looking into it!

2022-09-10 08:08 UTC, agateau requested changes
Looks good overall, just a few minor things to change:
- No need to commit the `pt_BR.mo` file, can you remove it?
- It seems you have renamed the pl.po file to pt_BR.po: this removed the Polish translation :/ Can you restore it?

2022-09-10 08:08 UTC, agateau commented on android/assets/ui/languages.xml
> +    <Language id="pt_BR" name="PortugueseBR" fontSet="xolonium-kwajong"/>
The text in the `name` attribute is the one shown in the language list. You can see it in this screenshot:
![screenshot-2022-09-10-100053 052](https://user-images.githubusercontent.com/3575/189474740-596deb7d-873e-4f9e-aaeb-f1578637e620.png)

This text should be written in the language of the translation itself, can you change it to say "Brazilian Portuguese" in Brazilian Portuguese?

2022-09-10 08:08 UTC, agateau commented on android/assets/screens/credits.gdxui
> +                <Label>PortugueseBR:</Label>
The text here is shown in the credits screen:
![screenshot-2022-09-10-100711 256](https://user-images.githubusercontent.com/3575/189474910-fc9f118e-7b44-4f68-9646-b4e8e217ffb2.png)

It should say something like "Brazilian Portuguese".

2022-10-14 06:07 UTC, agateau commented
I am planning to release Pixel Wheels 0.23.0 at the end of October / beginning of November. Do you think you can remaining issues? I would love to include your work in the next release!

2023-05-09 07:15 UTC, agateau commented
No activity here, I have to close the PR, sorry. Feel free to open a new one if you resume work on it.

2023-05-09 07:15 UTC, closed without merging

2023-05-09 13:42 UTC, Wilker-uwu commented
i don't remember much how it works on github. how do i pick up this pull request to continue? no promisses that i'll actually finish. i just wanna know this.