Ninjum patch 1
agateau/pixelwheels pull request #446
Opened 2024-07-04 22:24 UTC by ninjum

various corrections

2024-07-09 13:56 UTC, agateau requested changes
Hi @ninjum! Thanks a lot for this contribution. Just two minor remarks and it can be merged.

2024-07-09 13:56 UTC, agateau commented on android/assets/screens/credits.gdxui
> +                <Label>Galego:</Label>
The language should be in English here.

```suggestion
                <Label>Galician:</Label>
```

2024-07-09 13:56 UTC, agateau commented on android/assets/ui/languages.xml
> +    <Language id="gl" name="Galician" fontSet="xolonium-kwajong"/>
Here it's the other way around: the language should be translated.
```suggestion
    <Language id="gl" name="Galego" fontSet="xolonium-kwajong"/>
```

2024-07-09 15:10 UTC, ninjum commented
corrections made, is everything correct already?

2024-07-10 17:06 UTC, agateau approved these changes

2024-07-10 17:08 UTC, agateau commented
Looks good, thanks a lot!

2024-07-11 06:26 UTC, agateau commented
One last thing: I would need an email address to notify you when I am preparing a new release, so that you can update your translation. Can you send me your email address to mail@agateau.com?

2024-07-11 06:26 UTC, merged